
openapi: 3.0.0
info:
  title: Core Service gRPC Gateway
  version: 1.0.0
  description: gRPC over HTTP/JSON via gRPC Gateway (if needed)
paths:
  /v1/users/{user_id}:
    get:
      summary: Get user by ID (via gRPC Gateway)
      operationId: GetUser
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        tenant_id:
          type: string
